framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        # dsn: 'null://null' # désactive l'envoi de mails
        # envelope:
            # recipients: ['david.hurtrel@gmail.com'] # envoie tous les mails à cette adresse

