twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        nom: 'Lucie LONCHAMP'
        metier: 'Développeuse Web Fullstack  - Alternance'
        domaine: 'Portfolio'

when@test:
    twig:
        strict_variables: true
