twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        contact_company: 'Table Top Games'
        contact_address: '12345 rue du Village'
        contact_zip: '12345'
        contact_city: 'Ville'
        contact_phone: '01 23 45 67 89'
        contact_email: 'contact@table-top-games.com'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        'public/img': images

when@test:
    twig:
        strict_variables: true
